### ISSUE TITLE
绑定对象时会报 android.content.res.Resources$NotFoundException: String resource ID #0x2

### ISSUE THREAD

**Issue by ChenBill** [hacknife/Briefness#1]
private static void injectTextView(TextView view, Object value) {
        if (value instanceof String) {
            view.setText((String) value);
        } else if (value instanceof Integer) {
            **view.setText((Integer) value); //这里报错**
        } else {
            Log.e("Briefness", "No match method and can not inject " + view.getClass().getSimpleName());
        }
    }

**Comment by iwdael** [comment]
资源ID有问题
